In [ ]:
# numpy is library which contains array that store data in only one datatype
import numpy as np
a= np.array([1,2,3,4,'2'])
print (a)

['1' '2' '3' '4' '2']


In [ ]:
# Question 2
np_arr= np.array([3,3,3,3.3,'hello',False])
print(np_arr[-1])
print(bool (np_arr[-1]))

a= False
print(bool(a))

False
True
False


In [ ]:
# Function in numpy .............
a= np.zeros(3)
print (a)
print(type(a[0]))

# this function gives a matrix of given dimension filled with 0
b= np.zeros((2,3))
print(b)

c=np.zeros((2,3,4))
print(c)

# by default the datatype of array's element is float we can change it by argument called dtype
d=np.zeros((2,3),dtype=int)
print(d)

# this function gives a matrix of given dimension filled with 1
e=np.ones(2)
print(e)

# this function gives a matrix of given dimension filled with random element
f=np.empty(4,dtype=int)
print(f)

# this function gives a matrix of given dimension filled with particulat number [size,element]
g=np.full(4,5,dtype=int)
print(g)

[0. 0. 0.]
<class 'numpy.float64'>
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[0 0 0]
 [0 0 0]]
[1. 1.]
[1 2 3 4]
[5 5 5 5]


In [ ]:
# arange function gives an array filled with particular range [start,end]
a=np.arange(3,8)
print(a)

# linspace function gives an array of random value in a particular range [start, end, no. of element , endpoint=true(by default)]
b=np.linspace(3,8,4)
print(b)

[3 4 5 6 7]
[3.]


In [ ]:
# Array Inspection

# shape
a=np.array([[2,4,5],[6,7,8]])
print(a.shape)

#size
print(a.size)



(2, 3)
6


In [ ]:
import random

# gives a list of random numbers in a range (start,stop,numbers)
a= np.random.randint(1,7,4)
print(a)

# gives a list of random choice from the given list (list, choices)
b=np.random.choice([2,3,4,5],7)
print(b)


[2 6 3 1]
[2 4 3 5 4 4 5]


In [ ]:
a= np.random.randint(2,9,5)
b= np.random.randint(3,9,5)
print(a)
print(b)
print(a*2)
print("Add")
print(a+b)
print("multiple")
print(a*b)
print("divide")
print(a/b)
print("sub")
print(a-b)


[7 7 3 5 6]
[8 7 7 6 4]
[14 14  6 10 12]
Add
[15 14 10 11 10]
multiple
[56 49 21 30 24]
divide
[0.875      1.         0.42857143 0.83333333 1.5       ]
sub
[-1  0 -4 -1  2]


In [ ]:
a=[2,4,5,6]
b=[4,5,6,9]
print(a*2)
print(a+b)
# Note: in numpy array all operations are valid but in normal list multiply of list results in duplication
# of element and addition results in concatenation

[2, 4, 5, 6, 2, 4, 5, 6]
[2, 4, 5, 6, 4, 5, 6, 9]


In [ ]:
a = np.random.randint(2,15,6)

# reshape
b=a.reshape((2,3))
print(b)
#transpose
print(b.transpose())


[[12  9  2]
 [14 10  9]]
[[12 14]
 [ 9 10]
 [ 2  9]]


In [ ]:
a=np.random.randint(1,8,6)
c=a.reshape(2,3)
b=np.random.randint(2,8,6)
d=b.reshape(2,3)
# we have to pass the argument of concatenate function in tuple
print(np.concatenate((c,d),axis=1))

[[7 1 4 2 7 4]
 [7 6 4 4 5 2]]


In [ ]:
a=np.random.randint(2,25,6)
b=np.random.randint(1,19,6)
# syntax of where function [condition,x,y]
# it checks condition if condition is true then results x , else y
c=np.where(b>2,b,a)
print(c)

[ 3 16  5 13  7  4]


In [ ]:
# Question #
import numpy as np
a=[]
days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
for i in range(7):
  score=int(input(f"Score of {days[i]}:"))
  a.append(score)

c=np.array(a)

max_score=c.max()
print("Maximum score: ",max_score)

min_score=c.min()
print("Minimum score: ",min_score)

total_score=c.sum()
print("Total sum:",total_score)

score_mean=c.mean()
print("Mean:",score_mean)

std_score=c.std()
print("Standard Deviation:",std_score)






Score of Monday:2
Score of Tuesday:3
Score of Wednesday:4
Score of Thursday:5
Score of Friday:6
Score of Saturday:7
Score of Sunday:8
[2, 3, 4, 5, 6, 7, 8]
Maximum score:  8
Minimum score:  2
Total sum: 35
Mean: 5.0
Standard Deviation: 2.0


In [ ]:
# Homework ..........
import numpy as np

products = []
prices = []

n = int(input("Enter number of products: "))

for i in range(n):
    product = input(f"Enter name of product {i+1}: ")
    price = float(input(f"Enter price of {product}: "))

    products.append(product)
    prices.append(price)

p = np.array(prices)

print("\nProducts and Prices:")
for i in range(n):
    print(products[i], ":", prices[i])

print("\nHighest Price:", p.max())
print("Lowest Price:", p.min())
print("Total Price:", p.sum())
print("Average Price:", p.mean())
print("Standard Deviation:", p.std())


Enter number of products: 3
Enter name of product 1: Noddles
Enter price of Noddles: 50.6
Enter name of product 2: Clothes
Enter price of Clothes: 1500
Enter name of product 3: Watch
Enter price of Watch: 15000

Products and Prices:
Noddles : 50.6
Clothes : 1500.0
Watch : 15000.0

Highest Price: 15000.0
Lowest Price: 50.6
Total Price: 16550.6
Average Price: 5516.866666666666
Standard Deviation: 6731.644348564143
